sound/voice_commands/barney/help1.ogg
sound/voice_commands/barney/sorry1.ogg
sound/voice_commands/barney/sorry2.ogg
sound/voice_commands/barney/sorry3.ogg
sound/voice_commands/barney/sorry4.ogg
sound/voice_commands/fgrunt/cheer1.ogg
sound/voice_commands/fgrunt/cheer2.ogg
sound/voice_commands/fgrunt/cheer3.ogg
sound/voice_commands/fgrunt/cheer4.ogg
sound/voice_commands/fgrunt/help1.ogg
sound/voice_commands/fgrunt/sorry1.ogg
sound/voice_commands/fgrunt/welcome1.ogg
sound/voice_commands/gman/chat1.ogg
sound/voice_commands/gman/chat2.ogg
sound/voice_commands/gman/chat3.ogg
sound/voice_commands/gman/chat4.ogg
sound/voice_commands/gman/chat5.ogg
sound/voice_commands/gman/cheer1.ogg
sound/voice_commands/gman/cheer2.ogg
sound/voice_commands/gman/cheer3.ogg
sound/voice_commands/gman/die1.ogg
sound/voice_commands/gman/die2.ogg
sound/voice_commands/gman/die3.ogg
sound/voice_commands/gman/die4.ogg
sound/voice_commands/gman/follow1.ogg
sound/voice_commands/gman/hello1.ogg
sound/voice_commands/gman/hello2.ogg
sound/voice_commands/gman/help1.ogg
sound/voice_commands/gman/help2.ogg
sound/voice_commands/gman/no1.ogg
sound/voice_commands/gman/no2.ogg
sound/voice_commands/gman/no3.ogg
sound/voice_commands/gman/run1.ogg
sound/voice_commands/gman/sorry1.ogg
sound/voice_commands/gman/sorry2.ogg
sound/voice_commands/gman/sorry3.ogg
sound/voice_commands/gman/stop1.ogg
sound/voice_commands/gman/thanks1.ogg
sound/voice_commands/gman/thanks2.ogg
sound/voice_commands/gman/thanks3.ogg
sound/voice_commands/gman/welcome1.ogg
sound/voice_commands/gman/withyou1.ogg
sound/voice_commands/gman/yes1.ogg
sound/voice_commands/otis/cheer1.ogg
sound/voice_commands/otis/sorry1.ogg
sound/voice_commands/scientist/cheer1.ogg
sound/voice_commands/scientist/cheer2.ogg
sound/voice_commands/scientist/cheer3.ogg
sound/voice_commands/scientist/cheer4.ogg
sound/voice_commands/scientist/help1.ogg
sound/voice_commands/scientist/help2.ogg
sound/voice_commands/scientist/run1.ogg
sound/voice_commands/scientist/run2.ogg
sound/voice_commands/scientist/sorry1.ogg
sound/voice_commands/scientist/sorry2.ogg
sound/voice_commands/scientist/sorry3.ogg
sound/voice_commands/scientist/thanks1.ogg
sound/voice_commands/scientist/thanks2.ogg
sound/voice_commands/scientist/welcome1.ogg
sprites/voice_commands/chat.spr
sprites/voice_commands/cheer.spr
sprites/voice_commands/dead.spr
sprites/voice_commands/follow.spr
sprites/voice_commands/hello.spr
sprites/voice_commands/help.spr
sprites/voice_commands/no.spr
sprites/voice_commands/run.spr
sprites/voice_commands/sorry.spr
sprites/voice_commands/stop.spr
sprites/voice_commands/taunt.spr
sprites/voice_commands/thanks.spr
sprites/voice_commands/welcome.spr
sprites/voice_commands/withyou.spr
sprites/voice_commands/yes.spr